eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8096

spring:
  application:
    name: User
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/geopportunity
    hikari:
      username: postgres
      password: 123


application:
  config:
    DataCANDIDAT-url: http://localhost:8095/api/vi/candidats
    DataRECRUTEUR-url: http://localhost:8095/api/vi/recruteurs
