eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8093

spring:
  application:
    name: Offres
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/geopportunity
    hikari:
      username: postgres
      password: 123


application:
  config:
    DataOFFRE-url: http://localhost:8095/api/vi/offres
