eureka:
  client:
    fetch-registry: false

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            - id: MicroService_User
              uri: http://localhost:8096
              predicates:
                - Path=/user/**
              metadata:
                cors:
                  allowedOrigins: '*'
                  allowedMethods:
                    - GET
                    - POST
                  allowedHeaders: '*'

            - id: MicroService_User_Entreprsie
              uri: http://localhost:8096
              predicates:
                - Path=/entreprise/**
              metadata:
                cors:
                  allowedOrigins: '*'
                  allowedMethods:
                    - GET
                    - POST
                  allowedHeaders: '*'

            - id: MicroService_Offre
              uri: http://localhost:8093
              predicates:
               - Path=/offre/**
              metadata:
                cors:
                  allowedOrigins: '*'
                  allowedMethods:
                    - GET
                    - POST
                  allowedHeaders: '*'

            - id: MicroService_Offre_Entreprise
              uri: http://localhost:8093
              predicates:
                - Path=/entreprise/**
              metadata:
                cors:
                  allowedOrigins: '*'
                  allowedMethods:
                    - GET
                    - POST
                  allowedHeaders: '*'

